// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6v4YKjtpSMXb8pyHglu7XzB9GAJUrE7E',
    appId: '1:699371369286:android:7320a02d2c0162c6db6b47',
    messagingSenderId: '699371369286',
    projectId: 'petmonitor-c7799',
    storageBucket: 'petmonitor-c7799.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLhIHtn7iKr3ngfTY5K3LJWourL4-AzL0',
    appId: '1:699371369286:ios:0df3fb9e6019a312db6b47',
    messagingSenderId: '699371369286',
    projectId: 'petmonitor-c7799',
    storageBucket: 'petmonitor-c7799.firebasestorage.app',
    iosClientId: '699371369286-8c6fsa0g6fhvhhiohnilbstfkamvdnlm.apps.googleusercontent.com',
    iosBundleId: 'com.petmonitor.petmonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyG6hUHwLmLrIYiJPaC7eRjYrjw8ya2bE',
    appId: '1:699371369286:web:e54fed71a237ac64db6b47',
    messagingSenderId: '699371369286',
    projectId: 'petmonitor-c7799',
    authDomain: 'petmonitor-c7799.firebaseapp.com',
    storageBucket: 'petmonitor-c7799.firebasestorage.app',
    measurementId: 'G-VMF35KYTC5',
  );
}
